version: "3"

services: 
  app:
    container_name: admin_con
    restart: always
    build: .
    ports:
      - '4000:4000'
    networks: 
      - codynators_net

networks: 
  codynators_net: 
    external: true