version: "3"

services: 
  admin:
    build: 
      context: .
      dockerfile: ./Admin/dockerfile
    ports: 
      - 4000:4000
    volumes: 
      - .:/Admin
      - '/Admin/node_modules'
    depends_on: 
      - mysql_server
  
  mysql_server:
    platform: linux/x86_64
    image: mysql:8.0.26
    environment: 
      - MYSQL_DATABASE=shopdb
      - MYSQL_USER=codynators
      - MYSQL_PASSWORD=codynators1!
      - MYSQL_ROOT_PASSWORD=rhgustjr9402!