version: "3"

services: 
  app:
    build: 
      context: .
      dockerfile: dockerfile
    ports: 
      - 3000:3000
    volumes: 
      - .:/app
      - '/app/node_modules'
    depends_on: 
      - mysql_server
  
  mysql_server:
    platform: linux/x86_64
    image: mysql:8.0.26
    environment: 
      - MYSQL_DATABASE=shopdb
      - MYSQL_USER=codynators
      - MYSQL_PASSWORD=codynators1!
      - MYSQL_ROOT_PASSWORD=rhgustjr9402!