version: "3"

services: 
  mysql_server:
    platform: linux/x86_64
    image: mysql:8.0.26
    environment: 
      - MYSQL_DATABASE=shopdb
      - MYSQL_USER=codynators
      - MYSQL_PASSWORD=codynators1!
      - MYSQL_ROOT_PASSWORD=rhgustjr9402!
    volumes:
      - './mysql_volume:/var/lib/mysql'
  app:
    container_name: user_con
    restart: always
    build: .
    ports:
      - '3000:3000'
    external_links:
      - mysql_server