//2017156011 김현수
global:
  scrape_interval: 3s
  external_labels:
    monitor: 'Monitoring'
scrape_configs:
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['118.222.85.227:9090']
  - job_name: 'cAdvisor' 
    static_configs:
      - targets: ['118.222.85.227:8080']
