global:
  scrape_interval: 3s
  external_labels:
    monitor: 'Monitoring'
scrape_configs:
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['local IP:9090']
  - job_name: 'cAdvisor' 
    static_configs:
      - targets: ['local IP:8080']
