version: '3'
services:
  app:
    container_name: shop_con
    restart: always
    build: .
    ports:
      - '4001:4001'
    external_links:
      - mongo
    networks: 
      - codynators_net

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - ./mongo_volume:/data/db
    networks: 
      - codynators_net

networks: 
  codynators_net: 
    external: true